[package]
name = "contextforge-gateway-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
keywords.workspace = true


[dependencies]
contextforge-gateway-rs-cpex.workspace = true
contextforge-gateway-rs-lib.workspace = true
cpex-payload-marker = { workspace = true, optional = true }
cpex-text-prefixer = { workspace = true, optional = true }
cpex-tool-namespace = { workspace = true, optional = true }
clap.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
tonic.workspace = true
num_cpus.workspace = true
rmcp.workspace = true
tikv-jemallocator.workspace = true
rustls.workspace = true

[features]
test-plugins = ["dep:cpex-payload-marker", "dep:cpex-text-prefixer", "dep:cpex-tool-namespace"]

[lints]
workspace = true
