[package]
name = "contextforge-gateway-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
keywords.workspace = true


[dependencies]
contextforge-gateway-rs-cpex.workspace = true
contextforge-gateway-rs-lib = { path = "../contextforge-gateway-rs-lib" }
cpex-payload-marker = { git = "https://github.com/contextforge-gateway-rs/cpex-plugins-rs", rev = "ab47801daccfbba44ea07b033034a347e7b5afdd", optional = true }
cpex-text-prefixer = { git = "https://github.com/contextforge-gateway-rs/cpex-plugins-rs", rev = "ab47801daccfbba44ea07b033034a347e7b5afdd", optional = true }
cpex-tool-namespace = { git = "https://github.com/contextforge-gateway-rs/cpex-plugins-rs", rev = "ab47801daccfbba44ea07b033034a347e7b5afdd", optional = true }
secrets_detection_rust = { path = "../../../cpex-plugins/experiments/secrets_detection_rust", optional = true }
clap.workspace = true
tracing.workspace = true
tracing-appender = "0.2.3"
tracing-opentelemetry.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp = { version = "0.32", features = ["grpc-tonic", "http-proto", "reqwest-blocking-client", "metrics"] }
opentelemetry_sdk.workspace = true
tonic = "0.14"
num_cpus = "1.17.0"
rmcp.workspace = true
tikv-jemallocator = "0.7.0"
rustls.workspace = true

[features]
secrets-detection-plugin = ["dep:secrets_detection_rust"]
test-plugins = ["dep:cpex-payload-marker", "dep:cpex-text-prefixer", "dep:cpex-tool-namespace"]

[lints]
workspace = true
