<<<<<<< HEAD
.PHONY: help docker-prod compose-up compose-down docs-serve
=======
SERVICES ?= nginx control-plane redis postgres pgbouncer data-plane fast_time_server register_fast_time
ARGS     ?=

# IBM detect-secrets hardened fork — pinned to the same commit used in mcp-context-forge.
DETECT_SECRETS_SPEC ?= git+https://github.com/ibm/detect-secrets.git@076672a9a01abdfc7ecee2e7d14f08cdccb73976

# Files excluded from secret scanning (lock files generated by tooling).
DETECT_SECRETS_EXCLUDE := '(?x)(Cargo\.lock$$|\.lock$$)|^\.secrets\.baseline$$'

.PHONY: help \
        docker-prod compose-up compose-down docs-serve \
        fmt fmt-check lint deny \
        pre-commit install-pre-commit-hooks configure-git \
        secrets-scan secrets-scan-all secrets-audit secrets-baseline
>>>>>>> 7aaeb99 (feat:added make pre-commit)

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-22s\033[0m %s\n", $$1, $$2}'

# ---------------------------------------------------------------------------
# Docker
# ---------------------------------------------------------------------------

docker-prod: ## Build production Docker image (contextforge-data-plane:latest) from docker/Dockerfile
	docker build -t contextforge-data-plane:latest -f docker/Dockerfile .

compose-up: ## Launch stack: nginx, control plane, redis, postgres, pgbouncer, dataplane, fast_time_server
	@docker image inspect contextforge-data-plane:latest >/dev/null 2>&1 || { \
		echo "Image contextforge-data-plane:latest not found. Run 'make docker-prod' first."; \
		exit 1; \
	}
	docker compose -f docker/docker-compose.yml up -d $(SERVICES) $(ARGS)

<<<<<<< HEAD
compose-down: ## Tear down the stack
	docker compose -f docker/docker-compose.yml stop nginx control-plane redis postgres pgbouncer data-plane fast_time_server register_fast_time

docs-serve: ## Serve the wiki book locally at http://127.0.0.1:3000
	mdbook serve _context/wiki --hostname 127.0.0.1 --port 3000 --open
=======
testing-down: ## Tear down the testing stack
	docker compose -f docker/docker-compose.yml stop $(SERVICES) $(ARGS)
compose-down: ## Tear down the stack
	docker compose -f docker/docker-compose.yml stop $(SERVICES) $(ARGS)

docs-serve: ## Serve the wiki book locally at http://127.0.0.1:3000
	mdbook serve _context/wiki --hostname 127.0.0.1 --port 3000 --open

# ---------------------------------------------------------------------------
# Rust format & lint
# ---------------------------------------------------------------------------

fmt: ## Format Rust code with rustfmt (modifies files)
	cargo fmt --all

fmt-check: ## Check Rust formatting without modifying files
	cargo fmt --all --check

lint: ## Lint Rust code with clippy (warnings → errors)
	cargo clippy --locked --workspace --all-targets -- -D warnings

deny: ## Run cargo-deny supply-chain checks (advisories + licenses)
	cargo deny check advisories licenses

# ---------------------------------------------------------------------------
# pre-commit
# ---------------------------------------------------------------------------

install-pre-commit-hooks: ## Install pre-commit git hooks into .git/hooks
	@if ! command -v pre-commit >/dev/null 2>&1; then \
		echo "pre-commit not found. Install it with one of:"; \
		echo "  uv tool install pre-commit"; \
		echo "  brew install pre-commit"; \
		exit 1; \
	fi
	pre-commit install
	@echo "✅ pre-commit hooks installed"

pre-commit: ## Run all pre-commit hooks against every file
	@if ! command -v pre-commit >/dev/null 2>&1; then \
		echo "pre-commit not found. Install it with one of:"; \
		echo "  uv tool install pre-commit"; \
		echo "  brew install pre-commit"; \
		exit 1; \
	fi
	@mkdir -p .cache/pre-commit-home .cache/tmp
	PRE_COMMIT_HOME='$(CURDIR)/.cache/pre-commit-home' \
	TMPDIR='$(CURDIR)/.cache/tmp' \
	pre-commit run --config .pre-commit-config.yaml --all-files --show-diff-on-failure

# ---------------------------------------------------------------------------
# Secret scanning  (IBM detect-secrets hardened fork)
# ---------------------------------------------------------------------------

secrets-scan: ## Scan changed files and update .secrets.baseline in place
	@if ! command -v detect-secrets >/dev/null 2>&1 && ! command -v uv >/dev/null 2>&1; then \
		echo "detect-secrets not found. Install it with:"; \
		echo "  uv tool install '$(DETECT_SECRETS_SPEC)'"; \
		exit 1; \
	fi
	@if command -v detect-secrets >/dev/null 2>&1; then \
		detect-secrets scan --update .secrets.baseline --use-all-plugins \
			--exclude-files $(DETECT_SECRETS_EXCLUDE); \
	else \
		uv tool run --from '$(DETECT_SECRETS_SPEC)' detect-secrets scan \
			--update .secrets.baseline --use-all-plugins \
			--exclude-files $(DETECT_SECRETS_EXCLUDE); \
	fi
	@echo "📊 Findings report:"
	@if command -v detect-secrets >/dev/null 2>&1; then \
		detect-secrets audit --report .secrets.baseline; \
	else \
		uv tool run --from '$(DETECT_SECRETS_SPEC)' detect-secrets audit --report .secrets.baseline; \
	fi

secrets-scan-all: ## Full-tree scan — regenerate .secrets.baseline from scratch
	@if ! command -v detect-secrets >/dev/null 2>&1 && ! command -v uv >/dev/null 2>&1; then \
		echo "detect-secrets not found. Install it with:"; \
		echo "  uv tool install '$(DETECT_SECRETS_SPEC)'"; \
		exit 1; \
	fi
	@if command -v detect-secrets >/dev/null 2>&1; then \
		detect-secrets scan \
			--use-all-plugins \
			--exclude-files $(DETECT_SECRETS_EXCLUDE) \
			> .secrets.baseline; \
	else \
		uv tool run --from '$(DETECT_SECRETS_SPEC)' detect-secrets scan \
			--use-all-plugins \
			--exclude-files $(DETECT_SECRETS_EXCLUDE) \
			> .secrets.baseline; \
	fi
	@echo "✅ .secrets.baseline regenerated — audit new findings with: make secrets-audit"

secrets-audit: ## Interactive audit of unreviewed findings in .secrets.baseline
	@if command -v detect-secrets >/dev/null 2>&1; then \
		detect-secrets audit .secrets.baseline; \
	else \
		uv tool run --from '$(DETECT_SECRETS_SPEC)' detect-secrets audit .secrets.baseline; \
	fi

secrets-baseline: ## Alias for secrets-scan-all (initial baseline creation)
	@$(MAKE) --no-print-directory secrets-scan-all

# ---------------------------------------------------------------------------
# Git configuration
# ---------------------------------------------------------------------------

configure-git: install-pre-commit-hooks ## Configure git hooks + merge driver for .secrets.baseline
	@echo "🔀 Configuring git merge driver for .secrets.baseline..."
	@common_dir=$$(git rev-parse --git-common-dir); \
	mkdir -p "$$common_dir/git-drivers"; \
	cp scripts/git/resolve-secrets-baseline-conflict.sh "$$common_dir/git-drivers/"; \
	chmod +x "$$common_dir/git-drivers/resolve-secrets-baseline-conflict.sh"; \
	git config merge.secrets-baseline.name "Regenerate .secrets.baseline via detect-secrets-scan"; \
	git config merge.secrets-baseline.driver \
		"$$common_dir/git-drivers/resolve-secrets-baseline-conflict.sh %O %A %B %P"
	@echo "✅ Git merge driver configured for .secrets.baseline"
>>>>>>> 7aaeb99 (feat:added make pre-commit)
